kozily/web

- app/index.html
- app/index.jsx
- app/sum.jsx
- app/ui/application.jsx
- app/ui/application.sass
- app/ui/editor.jsx
- app/ui/icons.jsx
- app/ui/navbar.jsx
- app/ui/navbar.sass
- config/webpack.dev.js
- config/webpack.prod.js
- package.json
- specs/sum_spec.js
Implements a very basic header and a component encapsulating the ACE editor. It's configured for javascript now, as it's one of the built-in syntaxes the editor supports. We'll replace the mode once we have Oz syntax highlighting.
This also fixes a couple of hot reloading problems we had. Tested when developing all of this.
* Closes kozily/admin#34
> Implements a very basic UI

- app/index.html
- app/ui/application.jsx
- app/ui/editor.jsx
- app/ui/ide.jsx
- app/ui/navbar.jsx
- app/ui/navbar.sass
- config/webpack.dev.js
- config/webpack.prod.js
- package.json
This augments the basic UI bult at https://github.com/kozily/admin/issues/34. It replaces the integrated editor with a much more powerful one which has a better integration story with webpack, and it also supports Oz syntax highlighting out of the box.
* Closes kozily/admin#44
* Requires https://github.com/kozily/web/pull/4 merged first.
> Implement syntax highlighting

- app/oz/grammar.nearley
- specs/parser/number_spec.js
* Implements floating point literal parsing
* Closes kozily/admin#45
> Implement floating point literals

- app/oz/grammar.nearley
- specs/parser/number_spec.js
Implements character literal parsing
* Closes kozily/admin#47
> Implements character literal parsing

- app/oz/grammar/index.nearley
- app/oz/machine.js
- config/karma.js
- specs/machine/sequence_spec.js
- specs/parser/statements_sequence_spec.js
- specs/parser/whitespaces_spec.js
This implements both a recursive parser that allows infinite sequences of statements to be correctly parsed, as well as the mechanisms to execute such sequences in the abstract machine.
* Closes kozily/admin#37
> Implements the statement sequence statement

- app/oz/grammar/literals.nearley
- app/oz/grammar/literals_boolean.nearley
- specs/parser/literals_boolean_spec.js
Parsing of boolean literals has to work
* Closes kozily/admin#54
> Implements boolean literals

- app/oz/grammar/lexical.nearley
- specs/parser/lexical/record_spec.js
Implements a parser for the basic kernel syntax for records.
- Closes https://github.com/kozily/admin/issues/50
> Implement record syntax

- app/oz/grammar/index.nearley
- app/oz/machine.js
- app/oz/reducers/binding.js
- app/oz/reducers/index.js
- specs/parser/statements/local_spec.js
- specs/parser/statements/sequence_spec.js
- specs/parser/statements/skip_spec.js
- specs/parser/statements/varvar_binding_spec.js
- specs/reducers/varvar_binding_spec.js
- specs/samples/statements.js
- Implements simple variable-variable binding
- We still need to do complex partial value unification, but I'd like do that at the value creation statement implementation (see https://github.com/kozily/admin/issues/40).
- Closes kozily/admin#39
- Requires https://github.com/kozily/web/pull/14 merged first
- Some functionality deferred to https://github.com/kozily/admin/issues/40.
> Variable variable binding

- app/oz/grammar/lexical.nearley
- specs/parser/lexical/lists_spec.js
- specs/samples/lexical.js
Supports the parsing of list
* Closes kozily/admin#52
> Supports parsing lexical list

- app/oz/grammar/index.nearley
- app/oz/reducers/conditional.js
- app/oz/reducers/index.js
- specs/parser/statements/conditional_spec.js
- specs/reducers/conditional_spec.js
- specs/samples/statements.js
https://github.com/kozily/admin/issues/41
* Closes kozily/admin#41
> Conditional statement implementation

- app/oz/execution/exception_catch.js
- app/oz/execution/exception_context.js
- app/oz/execution/exception_raise.js
- app/oz/execution/index.js
- app/oz/free_identifiers/exception_catch.js
- app/oz/free_identifiers/exception_context.js
- app/oz/free_identifiers/exception_raise.js
- app/oz/free_identifiers/index.js
- app/oz/free_identifiers/pattern_matching.js
- app/oz/grammar/grammar.ne
- app/oz/machine/statements.js
- specs/execution/exception_catch_spec.js
- specs/execution/exception_context_spec.js
- specs/execution/exception_raise_spec.js
- specs/free_identifiers/exception_catch_spec.js
- specs/free_identifiers/exception_context_spec.js
- specs/free_identifiers/exception_raise_spec.js
- specs/parser/statements/exception_context_spec.js
- specs/parser/statements/exception_raise_spec.js
- specs/parser/statements/raise_spec.js
- specs/parser/statements/try_spec.js
- specs/samples/statements.js
Adds the full range of statements needed to enable exception handling in the kernel
* Closes kozily/admin#87
> 87 Exception handling

- app/oz/compilation/index.js
- app/oz/print/index.js
- app/state/parse.js
- app/state/store.js
- app/state/tabs.js
- app/ui/code/index.jsx
- app/ui/code/kernelEditor.jsx
- app/ui/navbar.jsx
- app/ui/workspace.jsx
Implements tabbed in visualization
* Closes kozily/admin#136
> 136 Implements tabbed visualization

- app/ui/code/index.jsx
- app/ui/runtime/stacks/threads.jsx
- app/ui/runtime/stores/index.jsx
Improvements on mobile devices
* Closes kozily/admin#150
> Mobile improvements

- app/oz/execution/sequence.js
- specs/execution/sequence_spec.js
Nested sequence statements are now flattened when executed.
* Closes kozily/admin#132
> 132 - Implements multisequence statement execution

- app/oz/runtime.js
- app/state/runtime.js
- app/ui/runtime/menu.jsx
- app/ui/runtime/stacks/index.jsx
- app/ui/runtime/stacks/thread.jsx
Implements manual scheduler in execution
* Closes kozily/admin#138
> Implements manual scheduler in execution

- app/oz/execution/pattern_matching.js
- app/oz/execution/sequence.js
- app/oz/free_identifiers/pattern_matching.js
- app/oz/grammar/grammar.ne
- app/oz/print/pattern_matching.js
- specs/compilation/pattern_matching_spec.js
- specs/execution/pattern_matching_spec.js
- specs/execution/sequence_spec.js
- specs/free_identifiers/conditional_spec.js
- specs/free_identifiers/pattern_matching_spec.js
- specs/parser/statements/pattern_matching_spec.js
- specs/print/pattern_matching_spec.js
* Fixes a regression issue on sequence of sequences which caused sequence to expand into the wrong stack ordering.
* Implements expressions on the case statement identifier.
* Closes kozily/admin#142
> 142 - Case statements now accept expressions

- app/state/parse.js
- app/state/runtime.js
- app/ui/code/error.jsx
- app/ui/code/index.jsx
- app/ui/runtime/error.jsx
- app/ui/runtime/index.jsx
Displaying runtime error
* Fixinig also the Message as a pre
* modify from errors to error
* Closes kozily/admin#144
> Uncaught exceptions should be displayed on the runtime screen

- app/ui/runtime/stacks/index.jsx
- app/ui/runtime/stacks/semantic_statement.jsx
- app/ui/runtime/stacks/thread.jsx
Adds a small button to trigger manual thread scheduling on the runtime.
* Connects kozily/admin#138
> 138 - Adds small icon to stacks to trigger manual scheduling

- app/oz/compilation/by_need.js
- app/oz/execution/by_need.js
- app/oz/execution/procedure_application.js
- app/oz/free_identifiers/by_need.js
- app/oz/grammar/grammar.ne
- app/oz/machine/build.js
- app/oz/machine/exceptions.js
- app/oz/machine/sigma.js
- app/oz/print/by_need.js
- specs/compilation/by_need_spec.js
- specs/execution/by_need_spec.js
- specs/execution/helpers.js
- specs/execution/procedure_application_spec.js
- specs/free_identifiers/by_need_spec.js
- specs/parser/statements/by_need_spec.js
- specs/print/by_need_spec.js
The procedure position in by need statements can now be an expression
* Closes kozily/admin#148
> 148 - Expressions in by need

- app/oz/compilation/exception_raise.js
- app/oz/execution/exception_raise.js
- app/oz/free_identifiers/exception_raise.js
- app/oz/grammar/grammar.ne
- app/oz/machine/exceptions.js
- app/oz/print/exception_raise.js
- app/oz/print/index.js
- app/state/runtime.js
- app/ui/runtime/error.jsx
- app/ui/runtime/stores/sigma.jsx
- specs/compilation/exception_raise_spec.js
- specs/execution/exception_raise_spec.js
- specs/execution/helpers.js
- specs/free_identifiers/exception_raise_spec.js
- specs/parser/statements/exception_raise_spec.js
- specs/print/exception_raise_spec.js
Raise statements now allow an expression to be used instead of an identifier
* Closes kozily/admin#147
> 147 - Implements expression evaluation on raise statements

- app/oz/execution/by_need.js
- app/oz/execution/exception_raise.js
- app/oz/execution/local.js
- app/oz/execution/pattern_matching.js
- app/oz/execution/procedure_application.js
- app/oz/execution/sequence.js
- app/oz/machine/build.js
- app/oz/machine/environment.js
- app/oz/machine/threads.js
- app/state/runtime.js
- app/ui/runtime/stacks/semantic_statement.jsx
- specs/execution/binding_spec.js
- specs/execution/by_need_spec.js
- specs/execution/exception_context_spec.js
- specs/execution/exception_raise_spec.js
- specs/execution/local_spec.js
- specs/execution/pattern_matching_spec.js
- specs/execution/procedure_application_spec.js
- specs/execution/sequence_spec.js
- specs/execution/skip_spec.js
- specs/execution/value_creation_spec.js
- specs/machine/threads/process_triggers_spec.js
Show the environments in the stack line
* Closes kozily/admin#133
> Show the environments in the stack line

- app/oz/built_ins/index.js
- app/oz/built_ins/isdet.js
- app/oz/built_ins/validations.js
- app/oz/execution/procedure_application.js
- app/oz/expression/operator.js
- app/oz/machine/build.js
- app/oz/print/values/built_in.js
- specs/built_ins/float_div_spec.js
- specs/built_ins/isdet_spec.js
- specs/built_ins/number_addition_spec.js
- specs/built_ins/number_division_spec.js
- specs/built_ins/number_modulo_spec.js
- specs/built_ins/number_multplication_spec.js
- specs/built_ins/number_subtraction_spec.js
- specs/built_ins/record_selection_spec.js
- specs/built_ins/value_entailment_spec.js
- specs/built_ins/value_greater_than_equal_spec.js
- specs/built_ins/value_greater_than_spec.js
- specs/built_ins/value_less_than_equal_spec.js
- specs/built_ins/value_less_than_spec.js
- specs/execution/procedure_application_spec.js
- specs/machine/initialization_spec.js
- specs/print/built_in_spec.js
Implements is determined builtin
* supports no namespaced built ins
* Closes kozily/admin#104
> Boundness test

- app/oz/built_ins/arity.js
- app/oz/built_ins/index.js
- app/oz/built_ins/label.js
- specs/built_ins/arity_spec.js
- specs/built_ins/label_spec.js
- specs/machine/initialization_spec.js
* Implements both the `Arity` and the `Label` built-in operations
* Closes kozily/admin#85
> 85 - Implements built-in record operations

- app/oz/built_ins/float.js
- app/oz/built_ins/index.js
- app/oz/built_ins/isdet.js
- app/oz/built_ins/number.js
- app/oz/built_ins/record.js
- app/oz/built_ins/value.js
- app/oz/built_ins/wait.js
- app/oz/execution/procedure_application.js
- specs/built_ins/wait_spec.js
- specs/execution/procedure_application_spec.js
- specs/machine/initialization_spec.js
Implements Wait built in operation
* Closes kozily/admin#106
> Built-in concurrency operations

- app/oz/grammar/grammar.ne
- app/oz/print/literals/record.js
- app/oz/print/values/record.js
- specs/parser/literals/lists_spec.js
- specs/print/record_literal_spec.js
- specs/print/record_value_spec.js
* Implements parsing of list conses.
* Implements pattern matching using list conses. This discovered a related issue which was detailed on https://github.com/kozily/admin/issues/158.
* Closes kozily/admin#89
> 89 - Implements the list cons literal

- app/oz/compilation/index.js
- app/oz/compilation/name_creation.js
- app/oz/entailment/index.js
- app/oz/entailment/name_creation.js
- app/oz/execution/index.js
- app/oz/execution/name_creation.js
- app/oz/free_identifiers/index.js
- app/oz/free_identifiers/name_creation.js
- app/oz/grammar/grammar.ne
- app/oz/machine/statementSyntax.js
- app/oz/machine/statements.js
- app/oz/machine/values.js
- app/oz/print/index.js
- app/oz/print/name_creation.js
- app/oz/print/values/name_creation.js
- app/oz/unification/index.js
- app/oz/unification/name_creation.js
- specs/compilation/name_creation_spec.js
- specs/entailment/name_creation_spec.js
- specs/execution/name_creation_spec.js
- specs/free_identifiers/name_creation_spec.js
- specs/parser/statements/name_creation_spec.js
- specs/print/name_creation_spec.js
- specs/unification/name_creation.js
Implementation of NewName
* Closes kozily/admin#112
> Implements Name creation

- app/state/runtime.js
- app/ui/runtime/menu.jsx
- app/ui/runtime/stacks/semantic_statement.jsx
- app/ui/runtime/stacks/thread.jsx
- app/ui/runtime/stores/index.jsx
- app/ui/runtime/stores/sigma.jsx
* Hide builtin variables in environment
* Closes kozily/admin#152
> Hide builtin variables in environment

- app/oz/compilation/cell_exchange.js
- app/oz/compilation/index.js
- app/oz/execution/cell_exchange.js
- app/oz/execution/index.js
- app/oz/free_identifiers/cell_exchange.js
- app/oz/free_identifiers/index.js
- app/oz/grammar/grammar.ne
- app/oz/machine/statementSyntax.js
- app/oz/machine/statements.js
- app/oz/print/cell_exchange.js
- app/oz/print/index.js
- specs/compilation/cell_exchange_spec.js
- specs/execution/cell_creation_spec.js
- specs/execution/cell_exchange_spec.js
- specs/execution/port_creation_spec.js
- specs/free_identifiers/cell_exchange_spec.js
- specs/parser/statements/cell_exchange_spec.js
- specs/print/cell_exchange_spec.js
* Implements the cell exchange kernel statement
* Closes kozily/admin#109
> 109 - Cell exchange

- app/oz/grammar/grammar.ne
- app/oz/grammar/program.ne
- app/oz/parser.js
- specs/parser/whitespaces_spec.js
Implements the proper handling of whitespaces and comments
* Closes kozily/admin#156
> Implements the handling of spaces and comments

- app/oz/compilation/expressions/conditional.js
- app/oz/compilation/expressions/exception_context.js
- app/oz/compilation/expressions/function.js
- app/oz/compilation/expressions/helpers.js
- app/oz/compilation/expressions/local.js
- app/oz/compilation/expressions/pattern_matching.js
- app/oz/compilation/expressions/thread.js
- app/oz/compilation/index.js
- app/oz/grammar/grammar.ne
- app/oz/machine/expressions.js
- specs/compilation/expressions/function_spec.js
- specs/compilation/expressions/thread_spec.js
- specs/parser/expressions/thread_spec.js
* Implements the thread statement expression
* Extracts a couple of helper functions to build expression compilations.
* Closes kozily/admin#170
> 170 - Thread expression
